"""empty message

Revision ID: 18fbb3ae1112
Revises: ae50afa445a8
Create Date: 2025-05-28 17:06:50.049103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18fbb3ae1112'
down_revision = 'ae50afa445a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('evaluator_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('evaluator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
