"""empty message

Revision ID: ae50afa445a8
Revises: 57f343ac69bd
Create Date: 2025-05-28 15:58:59.875748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae50afa445a8'
down_revision = '57f343ac69bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date_approved', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'employees', ['evaluator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date_approved')
        batch_op.drop_column('evaluator_id')

    # ### end Alembic commands ###
