"""empty message

Revision ID: b5e38cb7a6c2
Revises: a6871a9d404b
Create Date: 2025-05-28 19:05:15.694055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e38cb7a6c2'
down_revision = 'a6871a9d404b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('evaluator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('evaluator_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('evaluator_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('evaluator_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
